language: node_js
node_js:
- '0.10'

deploy:
  provider: npm
  email: t.wiszniewski@gmail.com
  api_key:
    secure: TpgNorhjeqXuXpbQLimANei4kXgt++3IfzM8M4xJtPbwEvPMckKAZ8pSMJOkKNKQA1zE+kOf4Nw5YnUZKh24X03sQIHIyyp7PAaaSHpcK3pzO4MHuIOH/yn3r7MaBjFuCaucH9RUX+5Acwt5Hlq3yHWGzzKZ1NCp5JIE/fzmo+o=
  on:
    tags: true
    all_branches: true
    repo: tomekwi/as.js
