language: node_js
node_js:
- '0.10'

deploy:
  provider: npm
  email: t.wiszniewski@gmail.com
  api_key:
    secure: lUuNf58BNObKKtTV3zvSzp3QGtFEnnjuy7tbcXAOwMt3U9JnMJRW0Tn607IEK3OfCjF/KxoUEf75UtFXNWyNN8XUBX1hXdoMtr4b305vnk0myPiZSgo24X29LvxURYYCZSlpAycY3y/+hmq0AWlIwAUX8P2NRM9JkyQ85AA7w/Y=
  on:
    tags: true
    all_branches: true
    repo: tomekwi/gulp-doxme
